### ISSUE TITLE
Representation closely matching vk.xml

### ISSUE THREAD

**Issue by krolli** [krolli/vk-parse#2]
Right now result of parsing is exposed using structures from external crates. Since I can't update those, supporting vulkan 1.1 changes in vk.xml format is problematic. Best solution seems to be having my own representation in addition to existing ones. This should help solve above mentioned problems and hopefully make it easier to map data structure to original vk.xml it was parsed from.

**Comment by MaikKlein** [comment]
Also it would be nice if the `Registry` would implement `Debug`

**Comment by krolli** [comment]
I already had that locally, but it was mixed among rather large changes I wanted to finish before pushing it. `Debug` is there now.
