### ISSUE TITLE
`UnexpectedAttribute` and `UnexpectedElement` errors

### ISSUE THREAD

**Issue by Rua** [krolli/vk-parse#22]
I'm getting parse errors when using this with vk.xml 1.2.203:
> The following errors were found while parsing the file:
> UnexpectedAttribute { xpath: "/registry/types/type/member", name: "objecttype" }
> UnexpectedAttribute { xpath: "/registry/types/type/member", name: "objecttype" }
> UnexpectedAttribute { xpath: "/registry/types/type/member", name: "objecttype" }
> UnexpectedAttribute { xpath: "/registry/types/type/member", name: "objecttype" }
> UnexpectedAttribute { xpath: "/registry/commands/command/param", name: "objecttype" }
> UnexpectedAttribute { xpath: "/registry/commands/command/param", name: "objecttype" }
> UnexpectedAttribute { xpath: "/registry/commands/command/param", name: "objecttype" }
> UnexpectedElement { xpath: "/registry/formats", name: "formats" }

The `objecttype` attribute was added in [1.2.182](https://github.com/KhronosGroup/Vulkan-Headers/commit/ab968ab2fce8d15cb9c8781a3cbe540d4b04f1e3#diff-a852a94832433f254f7e5ff6cf889035be373606623d793dfe4a75e535600cbe) and `formats` was added in [1.2.199](https://github.com/KhronosGroup/Vulkan-Headers/commit/83e1a9ed8ce289cebb1c02c8167d663dc1befb24#diff-a852a94832433f254f7e5ff6cf889035be373606623d793dfe4a75e535600cbe).

**Comment by Rua** [comment]
@MarijnS95 since Ash also uses this crate, is this an issue you've also run into?

**Comment by MarijnS95** [comment]
@Rua Ash's generator [does not log errors](https://github.com/MaikKlein/ash/blob/8f05905ecbc4cd4002c887c02c3022c41e0de1f0/generator/src/lib.rs#L2573) so I did not see these come by yet.

Perhaps we should change that.

**Comment by krolli** [comment]
Fixed in commit fc6203220bf10e8de01558b2e6ead6841a056073 .

Will be part of version 0.7.

**Comment by krolli** [comment]
Error logging is optional for users. I have periodic CI set up that tests master and a bunch of past versions of `vk.xml` and should let me know when they introduce something unsupported within a day or so. Unfortunately, travis-ci did some changes and silently disabled this plan, and I didn't notice it for over half a year. CI should be fixed now as well, though.

**Comment by MarijnS95** [comment]
We discussed the CI last time - perhaps I should start printing the logs in the `ash` generator since I'm generally the only one re-running that thing on every SDK update, so I'd notice as soon as there's something new and useful.

**Comment by krolli** [comment]
Yeah, CI seems to fail me about once every year or two. Maybe I should have some fallback...

Anyway, 0.7 is out.
