### ISSUE TITLE
Extension number is missing in vkxml

### ISSUE THREAD

**Issue by MaikKlein** [krolli/vk-parse#3]
The vk.xml currently defined some extensions like this
```
<enum extends="VkStructureType" extnumber="61"  offset="7 name="VK_STRUCTURE_TYPE_DEVICE_GROUP_PRESENT_CAPABILITIES_KHR"/>
```

But `extnumber` doesn't seem to be parsed by vkxml. Related to https://github.com/krolli/vk-parse/issues/2 .This is sadly currently a blocker for me, as I can't compute the correct value for those constants.

**Comment by krolli** [comment]
I already have some types for representing .rnc schema finished, which should give you access to everything that is in vkxml files. I tried to match names in .rnc and vk.xml as much as possible, only making changes where they clashed with rust keywords or where some older vk.xml versions didn't match .rnc.

You could try processing <feature> and <extensions> from these types. Here's what it looks like if you need to get to extensions:
```
let registry = vk_parse::parse_file(Path::new(&vk_xml));
for item in registry.0.iter() {
    match item {
        vk_parse::RegistryItem::Extensions { items, .. } => for item in items.iter() {
            process_extension(&item);
            process_vkxml_extension(&vkxml::Extension::from(item.clone()));
        },
        _ => (),
    }
}
```
From conversions are obviously lossy and I don't have them for everything yet, but that's probably not very important for you anyway. I don't have C parsing in there yet, but as far as I can tell, <feature> and <extensions> don't contain any of that anyway, so you might be able to process those already. Unfortunately, it will be a couple of days before I can get back to finishing this, but hopefully this will be enough for you to move forward.

**Comment by MaikKlein** [comment]
Yeah I don't really care if it is lossy. Thanks, I'll give it a try.
