### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by GabrielMajeri** [krolli/vk-parse#7]
Currently, it's unclear under which license is `vk-parse` published. Without an open source license, other people [cannot contribute or use the code](https://choosealicense.com/no-permission/) legally.

Considering that the official `vk.xml` is licensed under the Apache-2.0 license with an exception for GPL, it would make sense to also publish this under a similar license.

**Comment by krolli** [comment]
I planned to look into this once interface is more stable and crate is released on crates.io. I haven't given much thought to what license to use, but your suggestion makes a lot of sense and I think I'll go with that. I don't have much experience with setting these things up though, so if you know what needs to be done, I will gladly accept pull request with required changes.
